// @ts-check
import { defineConfig } from 'astro/config';
import react from '@astrojs/react';

// Static output = every page pre-rendered to full HTML (great for SEO/AI crawlers).
// Sitemap is generated by src/pages/sitemap.xml.ts (no external integration,
// so nothing to break on version bumps).
export default defineConfig({
  site: 'https://baycityblinds.com.au',
  output: 'static',
  integrations: [react()],
});
